import SwiftUI
import WebKit

/// SwiftUI wrapper around a hardened WKWebView.
///
/// Hardening applied:
///   - Ephemeral (non-persistent) data store globally → Ghost Mode by default,
///     no disk writes survive the session.
///   - document-start WKUserScript spoofing navigator/screen to the uniform
///     anonymity set (payload generated by @dhurta/core buildFingerprintScript).
///   - WebRTC disabled via injected block script (@dhurta/core buildWebRTCBlockScript).
///   - iOS 17+ per-datastore proxy → all WebKit egress through the embedded Tor loop.
///   - Compiled Safari Content Blocker rules for in-engine ad/tracker blocking.
struct WebContainerView: UIViewRepresentable {
    let url: URL
    let proxyConfig: ProxyConfiguration?
    let injectedScripts: [String]   // from @dhurta/core, delivered at build time
    let contentRuleList: WKContentRuleList?

    func makeUIView(context: Context) -> WKWebView {
        let controller = WKUserContentController()

        // Fingerprint + WebRTC block scripts, run in the page world at doc start.
        for source in injectedScripts {
            let script = WKUserScript(
                source: source,
                injectionTime: .atDocumentStart,
                forMainFrameOnly: false
            )
            controller.addUserScript(script)
        }

        // Native-speed ad/tracker blocking compiled from the shared blocklist.
        if let ruleList = contentRuleList {
            controller.add(ruleList)
        }

        let config = WKWebViewConfiguration()
        config.userContentController = controller
        config.allowsInlineMediaPlayback = true

        // Ghost Mode memory preservation — nothing touches disk.
        let dataStore = WKWebsiteDataStore.nonPersistent()

        // iOS 17+ proxy hooking — force every request through Tor's SOCKS loop.
        if #available(iOS 17.0, *), let proxy = proxyConfig {
            dataStore.proxyConfigurations = [proxy]
        }
        config.websiteDataStore = dataStore

        let webView = WKWebView(frame: .zero, configuration: config)
        webView.allowsBackForwardNavigationGestures = true
        webView.isOpaque = false
        webView.load(URLRequest(url: url))
        return webView
    }

    func updateUIView(_ webView: WKWebView, context: Context) {
        if webView.url != url {
            webView.load(URLRequest(url: url))
        }
    }
}
